---
- name: configure default routes
  cisco.ios.ios_static_routes:
    config:
    - address_families:
        afi: ipv6
        routes:
          - dest: 0.0.0.0/0
            next_hops:
            - forward_router_address: 192.168.0.250